Flight/Flight/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Flight1.urls'))
]

Flight/Flight1/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='Flight1'
urlpatterns = [
    path("",views.index, name='index'),
    path("login/",views.LoginClass.as_view(), name='login'),
    path("register/",views.RegisterClass.as_view(), name='register'),
    path("logout/",views.logoutdef, name='logout'),
    path("passwordchange", views.PasswordChangeClass.as_view(template_name='Flight1/passwordchange.html'), name='passchange'),
    path("flight", views.flight, name="flight"),
    path('contact', views.contact, name="contact"),
    path('privacy-policy', views.privacy_policy, name="privacy"),
    path('terms-and-conditions', views.terms_and_conditions, name="terms"),
    path('about-us', views.about_us, name="aboutus"),
]

Flight/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Flight1.urls'))
]

Flight1/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='Flight1'
urlpatterns = [
    path("",views.index, name='index'),
    path("login/",views.LoginClass.as_view(), name='login'),
    path("register/",views.RegisterClass.as_view(), name='register'),
    path("logout/",views.logoutdef, name='logout'),
    path("passwordchange", views.PasswordChangeClass.as_view(template_name='Flight1/passwordchange.html'), name='passchange')
    
]

Flight/Flight1/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.



class User(AbstractUser):
    
    phone_number = models.CharField( ("phone_number"),null=False, blank=False, unique=False, max_length=11)
    ID_code = models.CharField ( ("ID_code"),null=False, blank=False, unique=False, max_length=13)
    
    def __str__(self):
         return f"{self.id}: {self.first_name} {self.last_name}"
    

class Place(models.Model):
     code = models.CharField(max_length=3, null= False, blank = False)
     city = models.CharField(max_length=64, null= False, blank = False)
     country = models.CharField(max_length = 64, null= False, blank = False)
     airport = models.CharField(max_length= 64, null= False, blank = False)

     def __str__(self):
        return f"{self.code}: {self.city}, ({self.country})"
     
class Week(models.Model):
    number = models.IntegerField()
    name = models.CharField(max_length=32)

    def __str__(self):
        return f"{self.name} ({self.number})"
    
class Flight(models.Model):
    depart= models.ForeignKey(Place, on_delete=models.CASCADE, related_name="departures")
    destination = models.ForeignKey(Place, on_delete=models.CASCADE, related_name="arrivals")
    depart_time = models.TimeField(auto_now=False, auto_now_add=False)
    depart_day= models.ManyToManyField(Week, related_name="flight_of_the_days")
    duration = models.DurationField(null=False, blank=False)
    arrival_time = models.TimeField(auto_now=False, auto_now_add=False)
    plane = models.CharField(max_length=32)
    airline= models.CharField(max_length=32)
    economy_fare = models.FloatField(null=True)
    business_fare = models.FloatField(null=True)
    first_fare = models.FloatField(null=True)

    def __str__(self):
        return f"{self.id} {self.plane}: {self.depart} to {self.destination}"

Flight1/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    
    phone_number = models.CharField( ("phone_number"),null=False, blank=False, unique=False, max_length=11)
    ID_code = models.CharField ( ("ID_code"),null=False, blank=False, unique=False, max_length=13)
    
    def __str__(self):
         return f"{self.id}: {self.first_name} {self.last_name}"

Flight/Flight1/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm


class PasswordChangingForm(PasswordChangeForm):
        old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder': 'Old Password *'}))
        new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder': 'New Password *'}))
        new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder': 'New Password Confirmation *'}))
        class Meta:
            model = User
            fields =['old_password', 'new_password1', 'new_password2']


Flight1/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm

class PasswordChangingForm(PasswordChangeForm):
        old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder': 'Old Password *'}))
        new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder': 'New Password *'}))
        new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder': 'New Password Confirmation *'}))
        class Meta:
            model = User
            fields =['old_password', 'new_password1', 'new_password2']

Flight/Flight1/views.py
from django.shortcuts import render
from django.http import HttpResponse,  HttpResponseRedirect
from django.views import View
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordChangeView
from .forms import PasswordChangingForm
from .models import *
from datetime import datetime
from django.views.decorators.csrf import csrf_exempt
import math






# Create your views here.


def index(request):
    min_date = f"{datetime.now().date().year}-{datetime.now().date().month}-{datetime.now().date().day}"
    max_date = f"{datetime.now().date().year if (datetime.now().date().month+3)<=12 else datetime.now().date().year+1}-{(datetime.now().date().month + 3) if (datetime.now().date().month+3)<=12 else (datetime.now().date().month+3-12)}-{datetime.now().date().day}"
    if request.method == 'POST':
        origin = request.POST.get('Origin')
        destination = request.POST.get('Destination')
        depart_date = request.POST.get('DepartDate')
        seat = request.POST.get('SeatClass')
        trip_type = request.POST.get('TripType')
        if(trip_type == '1'):
            return render(request, 'Flight1/Home.html', {
            'origin': origin,
            'destination': destination,
            'depart_date': depart_date,
            'seat': seat.lower(),
            'trip_type': trip_type
        })
        elif(trip_type == '2'):
            return_date = request.POST.get('ReturnDate')
            return render(request, 'Flight1/Home.html', {
            'min_date': min_date,
            'max_date': max_date,
            'origin': origin,
            'destination': destination,
            'depart_date': depart_date,
            'seat': seat.lower(),
            'trip_type': trip_type,
            'return_date': return_date
        })
    else:
        return render(request, 'Flight1/Home.html', {
            'min_date': min_date,
            'max_date': max_date
        })


class LoginClass(View):
    def get(self,request):
         return render(request,'Flight1/login.html')
    
    def post(self,request):
        user_name =request.POST.get('tendangnhap')
        pass_word= request.POST.get('matkhau')
        my_user = authenticate(username=user_name,password=pass_word)
        if my_user is None:
             return render(request, "Flight1/login.html", {
                "message": "Invalid username and/or password."
            })
        login(request, my_user)
        return HttpResponseRedirect(reverse("Flight1:index"))

class RegisterClass(View):
    def get(self,request):
         return render(request,'Flight1/register.html')    
    
    def post(self,request):
        fname = request.POST['firstname']
        lname = request.POST['lastname']
        username = request.POST['username']
        email = request.POST['email']
        phone = request.POST['phone']
        IDcode = request.POST['identification']
       

        # Kiem tra mk trung khop
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "Flight1/register.html", {
                "message": "Passwords must match."
            })
        # Tao user moi
        else:
            try:
                new_user = User.objects.create_user(username, email, password)
                new_user.first_name = fname
                new_user.last_name = lname
                new_user.ID_code = IDcode
                new_user.phone_number = phone
                new_user.save()
            except:
                return render(request, "Flight1/register.html", {
                    "message": "Username already taken."
                })
            
            return render(request, "Flight1/register.html",{
                    "message": "Register successfully"})

class PasswordChangeClass (PasswordChangeView):
       form_class = PasswordChangingForm
       success_url = reverse_lazy('Flight1:index')
    
      
       
def logoutdef(request):
    logout(request)
    return HttpResponseRedirect(reverse("Flight1:index"))

@csrf_exempt
def flight(request):
    o_place = request.GET.get('Origin')
    d_place = request.GET.get('Destination')
    trip_type = request.GET.get('TripType')
    departdate = request.GET.get('DepartDate')
    depart_date = datetime.strptime(departdate, "%Y-%m-%d")
    return_date = None
    if trip_type == '2':
        returndate = request.GET.get('ReturnDate')
        return_date = datetime.strptime(returndate, "%Y-%m-%d")
        flightday2 = Week.objects.get(number=return_date.weekday()) ##
        origin2 = Place.objects.get(code=d_place.upper())   ##
        destination2 = Place.objects.get(code=o_place.upper())  ##
    seat = request.GET.get('SeatClass')

    flightday = Week.objects.get(number=depart_date.weekday())
    destination = Place.objects.get(code=d_place.upper())
    origin = Place.objects.get(code=o_place.upper())
    if seat == 'economy':
        flights = Flight.objects.filter(depart_day=flightday,depart=origin,destination=destination).exclude(economy_fare=0).order_by('economy_fare')
        try:
            max_price = flights.last().economy_fare
            min_price = flights.first().economy_fare
        except:
            max_price = 0
            min_price = 0

        if trip_type == '2':    ##
            flights2 = Flight.objects.filter(depart_day=flightday2,depart=origin2,destination=destination2).exclude(economy_fare=0).order_by('economy_fare')    ##
            try:
                max_price2 = flights2.last().economy_fare   ##
                min_price2 = flights2.first().economy_fare  ##
            except:
                max_price2 = 0  ##
                min_price2 = 0  ##
                
    elif seat == 'business':
        flights = Flight.objects.filter(depart_day=flightday,depart=origin,destination=destination).exclude(business_fare=0).order_by('business_fare')
        try:
            max_price = flights.last().business_fare
            min_price = flights.first().business_fare
        except:
            max_price = 0
            min_price = 0

        if trip_type == '2':    ##
            flights2 = Flight.objects.filter(depart_day=flightday2,depart=origin2,destination=destination2).exclude(business_fare=0).order_by('business_fare')    ##
            try:
                max_price2 = flights2.last().business_fare   ##
                min_price2 = flights2.first().business_fare  ##
            except:
                max_price2 = 0  ##
                min_price2 = 0  ##

    elif seat == 'first':
        flights = Flight.objects.filter(depart_day=flightday,depart=origin,destination=destination).exclude(first_fare=0).order_by('first_fare')
        try:
            max_price = flights.last().first_fare
            min_price = flights.first().first_fare
        except:
            max_price = 0
            min_price = 0
            
        if trip_type == '2':    
            flights2 = Flight.objects.filter(depart_day=flightday2,depart=origin2,destination=destination2).exclude(first_fare=0).order_by('first_fare')
            try:
                max_price2 = flights2.last().first_fare   
                min_price2 = flights2.first().first_fare  
            except:
                max_price2 = 0  
                min_price2 = 0  

    
    if trip_type == '2':
        return render(request, "Flight1/search.html", {
            'flights': flights,
            'origin': origin,
            'destination': destination,
            'flights2': flights2,   ##
            'origin2': origin2,    ##
            'destination2': destination2,    ##
            'seat': seat.capitalize(),
            'trip_type': trip_type,
            'depart_date': depart_date,
            'return_date': return_date,
            'max_price': math.ceil(max_price/100)*100,
            'min_price': math.floor(min_price/100)*100,
            'max_price2': math.ceil(max_price2/100)*100,    ##
            'min_price2': math.floor(min_price2/100)*100    ##
        })
    else:
        return render(request, "Flight1/search.html", {
            'flights': flights,
            'origin': origin,
            'destination': destination,
            'seat': seat.capitalize(),
            'trip_type': trip_type,
            'depart_date': depart_date,
            'return_date': return_date,
            'max_price': math.ceil(max_price/100)*100,
            'min_price': math.floor(min_price/100)*100
        })
    



def contact(request):
    return render(request, 'Flight1/contact.html')

def privacy_policy(request):
    return render(request, 'Flight1/privacy.html')

def terms_and_conditions(request):
    return render(request, 'Flight1/terms.html')

def about_us(request):
    return render(request, 'Flight1/about_us.html')

Flight1/views.py
from django.shortcuts import render
from django.http import HttpResponse,  HttpResponseRedirect
from django.views import View
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordChangeView
from .forms import PasswordChangingForm
from .models import *
# Create your views here.


def index(request):
    return render(request,'Flight1/Home.html')

class LoginClass(View):
    def get(self,request):
         return render(request,'Flight1/login.html')
    
    def post(self,request):
        user_name =request.POST.get('tendangnhap')
        pass_word= request.POST.get('matkhau')
        my_user = authenticate(username=user_name,password=pass_word)
        if my_user is None:
             return render(request, "Flight1/login.html", {
                "message": "Invalid username and/or password."
            })
        login(request, my_user)
        return HttpResponseRedirect(reverse("Flight1:index"))

class RegisterClass(View):
    def get(self,request):
         return render(request,'Flight1/register.html')    
    
    def post(self,request):
        fname = request.POST['firstname']
        lname = request.POST['lastname']
        username = request.POST['username']
        email = request.POST['email']
        phone = request.POST['phone']
        IDcode = request.POST['identification']
       

        # Kiem tra mk trung khop
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "Flight1/register.html", {
                "message": "Passwords must match."
            })
        # Tao user moi
        else:
            try:
                new_user = User.objects.create_user(username, email, password)
                new_user.first_name = fname
                new_user.last_name = lname
                new_user.ID_code = IDcode
                new_user.phone_number = phone
                new_user.save()
            except:
                return render(request, "Flight1/register.html", {
                    "message": "Username already taken."
                })
            
            return render(request, "Flight1/register.html",{
                    "message": "Register successfully"})

class PasswordChangeClass (PasswordChangeView):
       form_class = PasswordChangingForm
       success_url = reverse_lazy('Flight1:index')
    
      
       
def logoutdef(request):
    logout(request)
    return HttpResponseRedirect(reverse("Flight1:index"))

Flight/Flight1/templates/Flight1/about_us.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="{% static 'Flight1/css/about-us.css' %}">
    <script
      src="https://kit.fontawesome.com/64d58efce2.js"
      crossorigin="anonymous"
    ></script>
    <link rel="icon" href="{% static 'Flight1/img/planeicon.png' %}">
	<title>Weeboo | About</title>
    

</head>

<body>
    <img src="{% static 'Flight1/img/about_us.png' %}">
    <div class="container">
        <img src="{% static 'Flight1/img/work.png' %}" >
        <div class="content" >
            <div class="first-content">
                <h2>Who We Are</h2>
                <p>WEEBOO is your premier flight ticket manager, dedicated to simplifying and enhancing your travel experience. Established with a passion for travel and a commitment to innovation, we cater to the diverse needs of modern travelers.</p>
            </div>
            <div class="second-content">
                <h2>Our Vision</h2>
                <p>We envision a world where travel is a joyous adventure, unburdened by the complexities of ticket management. Through cutting-edge technology and a customer-centric approach, we aim to revolutionize the way you book, organize, and enjoy your flights.</p>
            </div>
        </div>
    </div>
</body>

</html>

Flight/Flight1/templates/Flight1/homelayout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'Flight1/img/planeicon.png' %}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&family=Rubik:wght@300&display=swap" rel="stylesheet"> 
    

    <link rel="stylesheet" href="{% static 'Flight1/css/homelayout.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.typekit.net/cav5lva.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    {% block head %}
    {% endblock %}
</head>
<body>

    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="{% url 'Flight1:index' %}">
            <img src="{% static 'Flight1/img/iconlogo.jpg' %}" height="50"  alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if not page %}active{% endif %}">
              <a class="nav-link" href="{% url 'Flight1:index' %}">Home</a>
            </li>
            <li class="nav-item {% if page == 'bookings' %}active{% endif %}">
              <a class="nav-link" href="#">Booking History</a>
            </li>
          </ul>
          <ul class="navbar-nav">
            {% if not user.is_authenticated %}
              <li class="nav-item">
                <button class="btn btn-outline-dark" style="border-radius: 25rem;" onclick="window.location.href = '/login';">
                  <svg width="1.1em" height="1.1em" viewBox="0 1.5 16 16" class="bi bi-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                  </svg>
                  Login
                </button>
              </li>
            {% else %}
              <li class="nav-item dropdown my-account">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  My Account
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <div class="dropdown-header" style="display: flex; padding: .5rem 1.2rem">
                    <div>
                        <svg width="1.5em" height="1.7em" viewBox="0 1 16 16" class="bi bi-person-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                          <path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z"/>
                          <path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                          <path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z"/>
                        </svg>
                    </div>
                    <div style="margin-left: 7%;">
                        {{user.first_name}} {{user.last_name}}
                    </div>
                  </div>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'Flight1:passchange' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1.1em" height="1.1em" fill="currentColor" class="bi bi-incognito" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="m4.736 1.968-.892 3.269-.014.058C2.113 5.568 1 6.006 1 6.5 1 7.328 4.134 8 8 8s7-.672 7-1.5c0-.494-1.113-.932-2.83-1.205a1.032 1.032 0 0 0-.014-.058l-.892-3.27c-.146-.533-.698-.849-1.239-.734C9.411 1.363 8.62 1.5 8 1.5c-.62 0-1.411-.136-2.025-.267-.541-.115-1.093.2-1.239.735m.015 3.867a.25.25 0 0 1 .274-.224c.9.092 1.91.143 2.975.143a29.58 29.58 0 0 0 2.975-.143.25.25 0 0 1 .05.498c-.918.093-1.944.145-3.025.145s-2.107-.052-3.025-.145a.25.25 0 0 1-.224-.274M3.5 10h2a.5.5 0 0 1 .5.5v1a1.5 1.5 0 0 1-3 0v-1a.5.5 0 0 1 .5-.5m-1.5.5c0-.175.03-.344.085-.5H2a.5.5 0 0 1 0-1h3.5a1.5 1.5 0 0 1 1.488 1.312 3.5 3.5 0 0 1 2.024 0A1.5 1.5 0 0 1 10.5 9H14a.5.5 0 0 1 0 1h-.085c.055.156.085.325.085.5v1a2.5 2.5 0 0 1-5 0v-.14l-.21-.07a2.5 2.5 0 0 0-1.58 0l-.21.07v.14a2.5 2.5 0 0 1-5 0v-1Zm8.5-.5h2a.5.5 0 0 1 .5.5v1a1.5 1.5 0 0 1-3 0v-1a.5.5 0 0 1 .5-.5"/>
                    </svg>
                    Change password
                  </a>
                  <a class="dropdown-item" href="{% url 'Flight1:logout' %}">
                    <svg width="1.1em" height="1.1em" viewBox="0 1.5 16 16" class="bi bi-power" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M5.578 4.437a5 5 0 1 0 4.922.044l.5-.866a6 6 0 1 1-5.908-.053l.486.875z"/>
                      <path fill-rule="evenodd" d="M7.5 8V1h1v7h-1z"/>
                    </svg>
                    Logout
                  </a>
                </div>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
 
  <main>
    {% block body %}{% endblock %}
    
  </main>


  
</div>
</body>
 
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="footer-col">
        <h4>WEEBOO</h4>
        <ul>
          <li><a href="{% url 'Flight1:contact' %}">Contact Us</a></li>
          <li><a href="{% url 'Flight1:aboutus' %}">About Us</a></li>
          <li><a href="{% url 'Flight1:privacy' %}">Privacy Policy</a></li>
          <li><a href="{% url 'Flight1:terms' %}">Terms and Conditions </a></li>
        </ul>
      </div>
      <div class="footer-col-2">
        <div class="logo-container">
          <img
            src="{% static 'Flight1/img/iconlogo.jpg' %}"
            height="90"
            width="260"
            style="border-radius: 5px"
          />
        </div>
        <div class="quote-container">Fly to the Heaven</div>
      </div>
    </div>
  </div>
</footer>
</html>

Flight/Flight1/templates/Flight1/layout2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
        <link rel="icon" href="{% static 'Flight1/img/planeicon.png' %}">
        <link rel="stylesheet" href="{% static 'Flight1/css/login.css' %}" >
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
        <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Onest"
      />
    </head>
    <body>
       {% block body %}
        {% endblock body %}
        
    </body>
</html>

Flight/Flight1/templates/Flight1/login.html
{% extends 'Flight1/layout2.html' %}
{% load static %}

    {% block title %}
    Weeboo | Login
    {% endblock title %}
    
</head>
{% block body %}
<body>
    <div class="wrapper">
        <form action="" method="post">
            {% csrf_token %} 
            <h1> Login <i class='bx bxs-plane-alt'></i>  </h1>
            <div class="input-box">
                <i class='bx bxs-user'> </i> Username
                <input type="text" name="tendangnhap" placeholder="Username *" autocomplete="off" required>
            </div>
            
            <div class="input-box">
                <i class='bx bxs-lock-alt'></i> Password
                
                <input type="password" name="matkhau" placeholder="Password *" autocomplete="off" required>
            </div>
            
            <div ><small>{{message}}</small></div>
            
            <br>
            <button class="btn">Login</button>
            <div class="register-links">
                <p style=" font-weight: bold;" >Don't have an account ? <a style="font-weight: bold;" href="{% url 'Flight1:register' %}" >Sign up</a></>
            </div>
        </form>
    </div>
</body>
{% endblock body %}